### ISSUE TITLE
Offer an aarch64 binary on the Jolla Store

### ISSUE THREAD

**Issue by llewelld** [hsjpekka/iCalendar-filters#2]
Currently there's only a 32-bit arm binary available on the Jolla Store. It would be great to also provide a package built for use on aarch64 devices as well.

I've built some packages which can be used for this if you like, inside the attached archive, Feel free to use them if that would be useful.

[harbour-icalendar-filters-.zip](https://github.com/hsjpekka/iCalendar-filters/files/15314706/harbour-icalendar-filters-.zip)

**Comment by hsjpekka** [comment]
Released.

**Comment by llewelld** [comment]
Great; thank you @hsjpekka!
